### ISSUE TITLE
2 joysticks type and events issues

### ISSUE THREAD

**Issue by alexichepura** [SergioRibera/virtual_joystick#1]
Hello, thank you for this library!

I'm trying it in bevy_garage https://github.com/alexichepura/bevy_garage/pull/62

2 issues:
- not receiving events if using 2 joysticks (single joystick works well)
- VirtualJoystickAxis is a resource, so not able to set 2 different types

![Screenshot 2023-04-15 at 11 09 38](https://user-images.githubusercontent.com/5582266/232199359-07a76240-32ee-4b2a-9f8d-298aa1d62662.jpg)

**Comment by SergioRibera** [comment]
> Hello, thank you for this library!
> 
> I'm trying it in bevy_garage https://github.com/alexichepura/bevy_garage/pull/62
> 
> 2 issues:
> - not receiving events if using 2 joysticks (single joystick works well)
> - VirtualJoystickAxis is a resource, so not able to set 2 different types
> 
> ![Screenshot 2023-04-15 at 11 09 38](https://user-images.githubusercontent.com/5582266/232199359-07a76240-32ee-4b2a-9f8d-298aa1d62662.jpg)
> 
> 

Ooooooh you're right, Although part of the code supports multiple joysticks, I have not taken that into account, let me fix it

**Comment by SergioRibera** [comment]
@alexichepura solved in [1.0.0](https://github.com/SergioRibera/virtual_joystick/tree/1.0.0) version

please update from [crates](https://crates.io/crates/virtual_joystick) and let me know what you think of the plugin, if you have any feedback, any functionality that you like or would like to develop, you are equally welcome to collaborate in whatever you want as you did with this issue, good luck in your project and again thank you for the report and for using my tool :D

**Comment by alexichepura** [comment]
fantastic! thank you! =)
implemented two joysticks similar to new example and confirming it works well on ios.
one nice addition would be "released" event, to reset value to 0 or i miss something (workarounded for now).

**Comment by SergioRibera** [comment]
> fantastic! thank you! =)
> implemented two joysticks similar to new example and confirming it works well on ios.

I am very glad that it is working, I would like to try it :D.

> one nice addition would be "released" event, to reset value to 0 or i miss something (workarounded for now).

At the moment I don't think the release event is needed because when you don't receive events is because you don't interact with any joystick, in the examples you can see that only the movements are made when you iterate on the received events, let me take a look at your implementation and check if it could be missing something, on the other hand, how easy was it to implement the library?

**Comment by alexichepura** [comment]
Right, no need for release event. I will rethink inputs/actions using leafwing input manager. Anyway it's need to set steering/gas/brake values to 0 when relevant input is released, but it's more app concern, less lib.
Thinking on consistency, bevy "gamepad_input_events" sends last event with 0 value. Sure, it's probably from hw device itself, virtual_joystick also goes to 0 visually but doesn't send such event with 0 value.
https://github.com/bevyengine/bevy/blob/main/examples/input/gamepad_input_events.rs
![Screenshot 2023-04-17 at 08 35 35](https://user-images.githubusercontent.com/5582266/232392806-0cf64b59-b9f1-4ff1-8ad4-3b74285d17a2.jpg)

PS1 great lib and it nicely integrates
PS2 started to work on android support for bevy_garage, hoping you'll try it later =)

**Comment by SergioRibera** [comment]
> Right, no need for release event. I will rethink inputs/actions using leafwing input manager. Anyway it's need to set steering/gas/brake values to 0 when relevant input is released, but it's more app concern, less lib.
> Thinking on consistency, bevy "gamepad_input_events" sends last event with 0 value. Sure, it's probably from hw device itself, virtual_joystick also goes to 0 visually but doesn't send such event with 0 value.
> https://github.com/bevyengine/bevy/blob/main/examples/input/gamepad_input_events.rs


Ooooh the idea that the last event is 0., I like it anyway, I was thinking about adding the type of event and I think it would be good to have something like:

```rs
pub enum VirtualJoystickEventType {
  Press,
  Drag,
  Up
}
```

This seems useful to me in multiple situations, in favor of your project and also the possibility of using the joystick as a button :0

I can bother you by asking you to open another suggestion issue about what you mention, I will try to make the last event always 0 and we will analyze the `VirtualJoystickEventType` option

**Comment by SergioRibera** [comment]
@alexichepura I added a fix so that when the joystick is released it sends an event with zero position in [1.0.1](https://github.com/SergioRibera/virtual_joystick/tree/1.0.1) version

**Comment by alexichepura** [comment]
Thank you! It works well.
