### ISSUE TITLE
Mobile browser touch events

### ISSUE THREAD

**Issue by clinuxrulz** [SergioRibera/virtual_joystick#16]
When targeting Web Assembly then running it on a mobile browser, it seems this plugin is looking for mouse events instead of touch events.

Maybe for desktop PC it should look for both touch events and mouse events. Plenty of laptops have touch screen these days.

```std::env::consts::OS``` contains an empty string for the Web Assembly target.

**Comment by SergioRibera** [comment]
Hi @clinuxrulz, I'm really sorry for the delay in answering you, I've been very busy preparing material for a talk I'm going to give.

I was contemplating this problem, and I was thinking about removing the validation, but now that you propose a solution, let me take a look at it.

**Comment by SergioRibera** [comment]
@clinuxrulz It seems to me that with PR complete, we can now close this issue, right?

**Comment by clinuxrulz** [comment]
Yes. Thank you!
