### ISSUE TITLE
Dynamic joystick adjustment

### ISSUE THREAD

**Issue by clinuxrulz** [SergioRibera/virtual_joystick#22]
**Is your feature request related to a problem? Please describe.**
Fix feel of dynamic joystick.

**Describe the solution you'd like**
Dynamic joystick should work and visually appear just like Floating joystick. However the joystick will move as the knob moves outside its interactive boundary. I.E. the joystick moves when needed to keep knob in boundary instead of moving knob to keep knob in boundary. I believe that is all we need to do to fix the feel of dynamic joystick.

The movement of the boundary would have to be in the same vector direction at the knob when the knob goes out of boundary too.

**Describe alternatives you've considered**
None

**Additional context**
The dynamic joystick in this project is call following joystick in this other project:
https://github.com/MarcoFazioRandom/Virtual-Joystick-Godot
Quote: "Following: When the finger moves outside the joystick area, the joystick will follow it.".

**Comment by SergioRibera** [comment]
I never liked the feel of the dynamic I made, I will be reviewing what you shared, if you can collaborate with any PR where this fits, I would appreciate it.

NOTE: For all the development of this library I tried to base on the Unity plugin.

**Comment by clinuxrulz** [comment]
If I get time, I can whip something up and see if you like the feel of it as a tester. I think just a very small change is needed code wise.

**Comment by SergioRibera** [comment]
Yes, I don't think it's a big change, but I need help because I haven't been able to give it a smooth or comfortable behavior

**Comment by clinuxrulz** [comment]
There is a pull request a long with a demo link for this one now.

See what you think.

**Comment by SergioRibera** [comment]
@clinuxrulz You're the best Man, I've been wanting to fix this for a while
