### ISSUE TITLE
Add Licensing?

### ISSUE THREAD

**Issue by nilaysavant** [SergioRibera/virtual_joystick#5]
Hello! This is a really nice library and I'm looking forward to trying it out!

Though you've mentioned the license in your [Cargo.toml](https://github.com/SergioRibera/virtual_joystick/blob/7e97149844649b8bc2cf05812caa8b06e8867bb4/Cargo.toml#L10) being `MIT OR Apache-2.0`, I would highly recommend adding the respective license file(s) in the repository.

This will make it clear about the library licensing and will also show up in the license sections on GitHub. Making it easier to find.

Here are the license files from the Bevy repository for reference: [MIT](https://github.com/bevyengine/bevy/blob/889a5fb13099e0978649033a892760a5714bde13/LICENSE-MIT) and [APACHE](https://github.com/bevyengine/bevy/blob/889a5fb13099e0978649033a892760a5714bde13/LICENSE-APACHE). Hope this helps.

Good luck with this 🚀

**Comment by SergioRibera** [comment]
Hey, thank you very much, it's really something I hadn't realized, when I get home I'll fix it.

Thank you very much also for your good comments and I hope that the library has really been of help to you :D

**Comment by SergioRibera** [comment]
Fixed, I just uploaded a [commit](https://github.com/SergioRibera/virtual_joystick/commit/eee7fa40bec9e14c46024abc3183a1c17de60ad2) with the license files, thank you very much.
